=== 0perator-dev/xml3year/chechko97/schema.dtd
<?xml version="1.0" encoding="UTF-8"?> 
<!ELEMENT catalogue (regions, vacations, people)>
<!ELEMENT regions (region)*>
<!ELEMENT vacations (vacation)*>
<!ELEMENT vacation (dates, stay, transport, price, schedule, includes)>
<!ELEMENT dates (date)+>
<!ELEMENT people (person)*>
<!ELEMENT person ((name)+, phoneNumber, EGN)>
<!ELEMENT schedule (day)+>
<!ELEMENT day (#PCDATA)>
<!ELEMENT includes (service)+>
<!ELEMENT service (#PCDATA)>

<!ATTLIST region id ID #REQUIRED>
<!ATTLIST vacation id ID #REQUIRED
					destination CDATA #REQUIRED
					photo ENTITY #IMPLIED
					region_id IDREF #IMPLIED>
<!ATTLIST day id ID #REQUIRED>
<!ATTLIST person id ID #REQUIRED
					person_id IDREF #IMPLIED>
<!ATTLIST date value CDATA #REQUIRED
				person_id IDREFS #IMPLIED>
<!ATTLIST service id ID #REQUIRED>

<!ELEMENT region (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT EGN (#PCDATA)>
<!ELEMENT stay (#PCDATA)>
<!ELEMENT transport (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT date (#PCDATA)>

<!NOTATION JPG SYSTEM "image/jpeg">

=== 0perator-dev/xml3year/chechko97/xml_project_61990_62106.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "schema.dtd" [
	<!ENTITY pict1 SYSTEM "https://rual-travel.com/uploads/gallery/karnaval-vyv-venetsiya-2017-variant-2-petdnevna-6_1482133717.jpg" NDATA JPG>
	<!ENTITY pict2 SYSTEM "https://rual-travel.com/uploads/gallery/karnaval-vyv-venetsiya-nitsa-i-manton-2017-4_1482133856.jpg" NDATA JPG>
	<!ENTITY pict3 SYSTEM "https://rual-travel.com/uploads/gallery/tsyala-skandinaviya-s-bergen-4_1496399317.jpg" NDATA JPG>
	<!ENTITY pict4 SYSTEM "https://rual-travel.com/uploads/gallery/dubay-osemdnevna-4_1543401919.jpg" NDATA JPG>
	<!ENTITY pict5 SYSTEM "https://rual-travel.com/uploads/gallery/izrael-po-svetite-mesta-5_1510836820.jpg" NDATA JPG>
	<!ENTITY pict6 SYSTEM "https://rual-travel.com/uploads/gallery/indiya-zlatniyat-triygylnik-mart-2018-4_1510745376.jpg" NDATA JPG>
	<!ENTITY pict7 SYSTEM "https://rual-travel.com/uploads/gallery/lisabon-treti-mart-2017-5_1482139655.jpg" NDATA JPG>
]>

<catalogue>	
	<regions>
		<region id="IT">Италия</region>
		<region id="FR">Франция</region>
		<region id="SCN">Скандинавия</region>
		<region id="DUB">Обединените арабски емирства</region>
		<region id="IZR">Израел</region>
		<region id="IND">Индия</region>
		<region id="PR">Португалия</region>
	</regions>
	
	<vacations>
		<vacation id="vac1" destination="Карнавал във Венеция" photo="pict1" region_id="IT">
			<dates>
				<date value="22.02.2019-26.02.2019" person_id="p1 p2 p3 p4"></date>
			</dates>
			<stay>
				5
			</stay>
			<transport>
				автобус
			</transport>
			<price>
				395
			</price>
			<schedule>
				<day id="d1">
					ПЪРВИ ДЕН - хотел “Тримонциум” в Пловдив – трансфер Пловдив – София за тези, които желаят, отпътуване от София – от Централна автогара София – сектор „Паркинг” по маршрут София – Белград – Загреб.
				</day>
				<day id="d2">
					ВТОРИ ДЕН - отпътуване за Верона. Разглеждане на Верона. Отпътуване към Лидо ди Йезоло или района на Тревизо.
				</day>
				<day id="d3">
					ТРЕТИ ДЕН - Разглеждане забележителностите на Венеция.
				</day>
				<day id="d4">
					ЧЕТВЪРТИ ДЕН - Свободен ден за разходки из карнавална Венеция.Вечерта - отпътуване по маршрут Венеция – Любляна – Загреб – Белград - София. Нощен преход.
				</day>
				<day id="d5">
					ПЕТИ ДЕН - Вечерта – пристигане в София на Централна автогара София, сектор “Паркинг”. Трансфер до Пловдив.	
				</day>
			</schedule>
			<includes>
				<service id="s1">
					ТРАНСПОРТ С ЛИЦЕНЗИРАН АВТОБУС;
				</service>
				<service id="s2">
					СЪОТВЕТНИЯ БРОЙ НОЩУВКИ СЪС ЗАКУСКИ;
				</service>
				<service id="s3">
					ВОДАЧ-ПРИДРУЖИТЕЛ;
				</service>
				<service id="s4">
					ЕКСКУРЗОВОДСКО ОБСЛУЖВАНЕ.
				</service>
			</includes>
		</vacation>
		<vacation id="vac2" destination="Карнавал в Ница и Мантон" photo="pict2" region_id="FR">
			<dates>
				<date value="27.02.2019-06.03.2019" person_id="p5 p6 p7"></date>
			</dates>
			<stay>
				8
			</stay>
			<transport>
				автобус
			</transport>
			<price>
				685
			</price>
			<schedule>
				<day id="d6">
					ПЪРВИ ДЕН - хотел “Тримонциум” в Пловдив – трансфер Пловдив – София   за тези, които желаят  – отпътуване от София, от Централна автогара София – сектор „Паркинг” по маршрут София – Белград – Загреб – Любляна – Венеция.
				</day>
				<day id="d7">
					ВТОРИ ДЕН - пристигане в карнавална Венеция. Разглеждане на града. Настаняване в хотела в Лидо ди Йезоло или района на Тревизо. Нощувка.
				</day>
				<day id="d8">
					ТРЕТИ ДЕН - Отпътуване за Ница. По пътя – двучасов престой в Сан Ремо, разходка из стария град - Ла Пиня. Вечерта – пристигане в Ница.
				</day>
				<day id="d9">
					ЧЕТВЪРТИ ДЕН - Разглеждане на Ница.
				</day>				
				<day id="d10">
					ПЕТИ ДЕН – Сутринта - разглеждане на Кан - бул. „Кроазет”, Фестивалния комплекс. Следобед - разходка до Мантон. Завръщане в Ница.
				</day>
				<day id="d11">
					ШЕСТИ ДЕН - Отпътуване от Ница. Разглеждане на Монако и Монте Карло, отпътуване за Италия. Вечерта - пристигане в района на Милано.
				</day>
				<day id="d12">
					СЕДМИ ДЕН – Разглеждане на Милано. Свободно време. Вечерта - отпътуване по маршрут Милано – Любляна – Загреб – Белград – София.
				</day>
				<day id="d13">
					ОСМИ ДЕН - Пристигане на Централна автогара София, сектор “Паркинг”. Трансфер до Пловдив.
				</day>
			</schedule>
			<includes>
				<service id="s5">
					ТРАНСПОРТ С ЛУКСОЗЕН АВТОБУС;
				</service>
				<service id="s6">
					СЪОТВЕТНИЯТ БРОЙ НОЩУВКИ СЪС ЗАКУСКИ;
				</service>
				<service id="s7">
					ВОДАЧ-ПРИДРУЖИТЕЛ ОТ ТУРОПЕРАТОРА;
				</service>
				<service id="s8">
					ЕКСКУРЗОВОДСКО ОБСЛУЖВАНЕ.
				</service>
			</includes>
		</vacation>
		<vacation id="vac3" destination="Цяла Скандинавия с Берген" photo="pict3" region_id="SCN">
			<dates>
				<date value="15.07.2019-29.07.2019" person_id="p8"></date>
			</dates>
			<stay>
				15
			</stay>
			<transport>
				автобус
			</transport>
			<price>
				1664
			</price>
			<schedule>
				<day id="d14">
					ПЪРВИ ДЕН – хотел “Тримонциум” в Пловдив – трансфер Пловдив – София за тези, които желаят – отпътуване от София от Централна автогара София, сектор “Паркинг” по маршрут София – Белград – Будапеща.
				</day>
				<day id="d15">
					ВТОРИ ДЕН - Отпътуване по маршрут Будапеща – Братислава – Бърно – Прага – Дрезден – Берлин. 
				</day>
				<day id="d16">
					ТТРЕТИ ДЕН - Панорамна обиколка на Берлин. През част от пътя се ползва ферибот за преминаване от Германия в Дания (Копенхаген).
				</day>
				<day id="d17">
					ЧЕТВЪРТИ ДЕН - Отпътуване за Швеция. Разглеждане на Малмьо. Вечерта - пристигане в Стокхолм.
				</day>				
				<day id="d18">
					ПЕТИ ДЕН - Туристическа програма в Стокхолм.
				</day>
				<day id="d19">
					ШЕСТИ ДЕН - Oтпътуване за Осло. Разходка из Вигеландпарк.
				</day>
				<day id="d20">
					СЕДМИ ДЕН - отпътуване за Согнефиорд – най-дългият фиорд в света и един от най-впечатляващите. Продължаване към Берген.
				</day>
				<day id="d21">
					ОСМИ ДЕН – Пълна обиколка на Берген. Свободно време.
				</day>
				<day id="d22">
					ДЕВЕТИ ДЕН – Отпътуване за Осло. Обиколка на.
				</day>
				<day id="d23">
					ДЕСЕТИ ДЕН - Отпътуване за Хелзингборг. По пътя – престой в Гьотеборг и разглеждане на центъра на града. 
				</day>
				<day id="d24">
					ЕДИНАДЕСЕТИ ДЕН - Отпътуване за Дания (пътят между шведския и датския бряг е половин час с ферибот). Посещение на замъка „Кронборг Слот. Пристигане в Копенхаген. Обиколка на града.
				</day>
				<day id="d25">
					ДВАНАДЕСЕТИ ДЕН - Закуска. Свободен ден в Копенхаген. Вечерта – отпътуване по маршрут Копенхаген – Берлин – Нюрнберг – Мюнхен – Залцбург – Виена.
				</day>				
				<day id="d26">
					ТРИНАДЕСЕТИ ДЕН - Пристигане в хотела във Виена.
				</day>
				<day id="d27">
					ЧЕТИРИНАДЕСЕТИ ДЕН - Пешеходна разходка из старата част на Виена с екскурзовод. Свободен следобед. Отпътуване по маршрут Виена – Будапеща – Белград – София. 
				</day>
				<day id="d28">
					ПЕТНАДЕСЕТИ ДЕН - пристигане на Централна автогара София, сектор “Паркинг”. Трансфер до Пловдив.
				</day>
			</schedule>
			<includes>
				<service id="s9">
					ТРАНСПОРТ С ЛИЦЕНЗИРАН АВТОБУС;
				</service>
				<service id="s10">
					СЪОТВЕТНИЯТ БРОЙ НОЩУВКИ СЪС ЗАКУСКИ;
				</service>
				<service id="s11">
					ВОДАЧ-ПРИДРУЖИТЕЛ ОТ ТУРОПЕРАТОРА;
				</service>
				<service id="s12">
					ЕКСКУРЗОВОДСКО ОБСЛУЖВАНЕ.
				</service>
			</includes>
		</vacation>
		<vacation id="vac4" destination="Дубай" photo="pict4" region_id="DUB">
			<dates>
				<date value="06.02.2019-13.02.2019" person_id="p9 p10 p11 p12 p13 p14"></date>
			</dates>
			<stay>
				8
			</stay>
			<transport>
				самолет
			</transport>
			<price>
				1368
			</price>
			<schedule>
				<day id="d29">
					ПЪРВИ ДЕН - Отпътуване от летище София за Дубай с директен полет на АК "Флай Дубай"; пристигане в Дубай. Трансфер до хотела. 
				</day>
				<day id="d30">
					ВТОРИ ДЕН –Полудневна панорамна обиколка на Дубай с екскурзовод на български (включена в цената). Свободно време.
				</day>
				<day id="d31">
					ТРЕТИ ДЕН - Свободен ден в Дубай или туристическа програма по желание: целодневна екскурзия до Абу Даби с екскурзовод на български, включен обяд и посещение на арабския Лувър.
				</day>
				<day id="d32">
					ЧЕТВЪРТИ ДЕН - Свободен ден в Дубай или туристическа програма по желание: Сутринта - полудневна екскурзия до Шарджа и Аджман (с доплащане 85 лв. за възрастен и 74 лв. за дете до 11 г. и при предварителна заявка и заплащане в България, а не на място).
				</day>				
				<day id="d33">
					ПЕТИ ДЕН - Свободен ден в Дубай или туристическа програма по желание: полудневен панорамен тур, включващ старата част на Дубай с екскурзовод на български – продължителност около 4 часа (с доплащане 92 лв. за възрастен и 82 лв. за дете до 11 г. и при предварителна заявка и заплащане в България, а не на място).
				</day>
				<day id="d34">
					ШЕСТИ ДЕН - Свободен ден в Дубай или туристическа програма по желание: посещение на Магическите градини (с доплащане 75 лв. за възрастен и 65 лв. за дете до 11 г. и при предварителна заявка и заплащане в България, а не на място).
				</day>
				<day id="d35">
					СЕДМИ ДЕН - Свободен ден в Дубай или туристическа програма по желание: целодневна екскурзия до града оазис Ал Айн с включен обяд – продължителност около 8 часа (с доплащане 195 лв. за възрастен и 185 лв. за дете до 11 г. и при предварителна заявка и заплащане в България, а не на място).
				</day>
				<day id="d36">
					ОСМИ ДЕН - Трансфер до летището. Отпътуване от Дубай за София.
				</day>
			</schedule>
			<includes>
				<service id="s13">
					ВОДАЧ - ПРИДРУЖИТЕЛ ОТ ТУРОПЕРАТОРА ПО ВРЕМЕ НА ЦЯЛАТА ПРОГРАМА;
				</service>
				<service id="s14">
					ДВУПОСОЧЕН САМОЛЕТЕН БИЛЕТ ЗА ДИРЕКТЕН ПОЛЕТ СОФИЯ – ДУБАЙ – СОФИЯ НА АК „ФЛАЙ ДУБАЙ”;
				</service>
				<service id="s15">
					ЛЕТИЩНИ ТАКСИ;
				</service>
				<service id="s16">
					1 ЧЕКИРАН БАГАЖ ДО 20 КГ.;
				</service>
				<service id="s17">
